
sudo: required
dist: trusty
language: node_js
node_js:
  - "lts/*"

before_script:
  - npm i npm@latest -g
  - npm install -g --silent @angular/cli@7.3.9

script:
  - ng lint
  - node --max_old_space_size=16384 ./node_modules/@angular/cli/bin/ng build --prod --output-hashing=none --base-href=\"/web-app/\"" --watch=false

deploy:
  provider: pages
  skip-cleanup: true
  local-dir: dist/web-app
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
